// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Person = __t.object("Person", {
  userid: __t.string(),
  passhash: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const Storage = __t.object("Storage", {
  ownerKey: __t.string(),
  value: __t.string(),
});
export type Storage = __Infer<typeof Storage>;

