// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChangePasswordReducer from "../change_password_reducer";
import SetitemReducer from "../setitem_reducer";
import SignupReducer from "../signup_reducer";

export type ChangePasswordParams = __Infer<typeof ChangePasswordReducer>;
export type SetitemParams = __Infer<typeof SetitemReducer>;
export type SignupParams = __Infer<typeof SignupReducer>;

